#+TITLE: Qtile
#+Subtitle: Like XMonad, but in python.
#+startup: fold
#+property: header-args :mkdirp yes
#+property: header-args:python :tangle config.py
#+auto_tangle: t
#+hugo_base_dir: ../../
#+hugo_type: config
#+hugo_section: wms
#+hugo_draft: false
#+hugo_bundle: qtile
#+export_file_name: index

This file serves as the documentation and source code for my configuration of Qtile.

* Global Imports
These must be imported in order for my config to work.
#+begin_details
#+begin_summary
_*Python*_
#+end_summary

#+begin_src python
import os
import re
import socket
import subprocess
from typing import List  # noqa: F401

from libqtile import layout, bar, widget, hook
from libqtile.lazy import lazy
from libqtile.config import Match, Screen, Group, DropDown, ScratchPad, KeyChord
from libqtile.config import EzKey as Key, EzClick as Click, EzDrag as Drag

from qtile_extras import widget

from theme import fonts
from theme import gruvbox as colors
#+end_src
#+end_details

* A Few Variables
I like to have the Super (or Windows) key as my modkey, alacritty as my terminal, and firefox as my browser.
#+begin_src python
mod = "mod4"
terminal = "alacritty"
browser = "firefox"
#+end_src


* Core Theming
:PROPERTIES:
:header-args:python: :tangle theme.py
:END:
This basic module describes my theme options for qtile.
** Colors
*** Gruvbox
I’ve been using gruvbox as my colorscheme for about a year now, and I really like it.
#+begin_src python
gruvbox = {
    "bg": "#282828",
    "bg-bright": "#32302f",
    "bg-dark": "#1d2021",
    "fg": "#ebdbb2",
    "red": "#cc241d",
    "green": "#98971a",
    "yellow": "#d79921",
    "blue": "#458588",
    "purple": "#b16286",
    "teal": "#689d6a",
    "orange": "#d65d0e",
    "gray": "#504945",
    }
#+end_src

*** TODO My Scheme
I am currently working on my own color scheme, and this is that scheme.
#+begin_src python
my_scheme = {}
#+end_src

** Fonts
I have 2 main fonts I like to use - a custom build of Iosevka for my text font, and Material Icons for my icons.
#+begin_src python
fonts = {
    "text": "Josevka Mono",
    "material": "Material Icons",
    "fa": "FontAwesome"
}
#+end_src

* Groups
Groups are your workspaces in Qtile.
#+begin_src python

# TODO Fix matching

groups = [Group("1", layout='monadtall'), ## Browser
          Group("2", layout='monadtall'), ## Emacs/Dev
          Group("3", layout='monadtall'), ## Terminal

          Group("4", layout='monadtall'), ## IRC/Discord
          Group("5", layout='monadtall'), ## Steam/Games
          Group("6", layout='monadtall'), ## Music
          Group("7", layout='max'), ## Graphics
          Group("8", layout='max'),
          Group("9", layout='max')]
#+end_src

* Keybindings
My keybindings aren't really that special - I try to keep them vim-based, or as close to vim-based as I can. I am organizing them based on a general category - such as my core bindings, other applications, etc.
#+begin_src python
keys = [
    Key("M-h", lazy.layout.left(), desc="Move focus to left"),
    Key("M-l", lazy.layout.right(), desc="Move focus to right"),
    Key("M-j", lazy.layout.down(), desc="Move focus down"),
    Key("M-k", lazy.layout.up(), desc="Move focus up"),
    Key("M-S-h", lazy.layout.shuffle_left(), desc="Move window to the left"),
    Key("M-S-l", lazy.layout.shuffle_right(), desc="Move window to the right"),
    Key("M-S-j", lazy.layout.shuffle_down(), desc="Move window down"),
    Key("M-S-k", lazy.layout.shuffle_up(), desc="Move window up"),
    Key("M-C-h", lazy.layout.grow_left(), desc="Grow window to the left"),
    Key("M-C-l", lazy.layout.grow_right(), desc="Grow window to the right"),
    Key("M-C-j", lazy.layout.grow_down(), desc="Grow window down"),
    Key("M-C-k", lazy.layout.grow_up(), desc="Grow window up"),
    Key("M-C-<equal>", lazy.layout.grow()),
    Key("M-C-<minus>", lazy.layout.shrink()),
    Key("M-C-0", lazy.layout.reset()),

    Key("M-S-q", lazy.window.kill(), desc="Kill focused window"),
    Key("M-S-r", lazy.restart(), desc="Restart Qtile"),
    Key("M-S-p", lazy.spawn("rofi -show powermenu -theme-str 'window { height: 55%;}' "), desc="Manage machine power state"),
    Key("M-f", lazy.window.toggle_fullscreen(), desc="Toggle fullscreen"),
    Key("M-S-f", lazy.window.toggle_floating(), desc="Toggle floating layout"),

    Key("M-<Tab>", lazy.next_layout()),
    Key("<XF86AudioLowerVolume>", lazy.spawn("pactl set-sink-volume @DEFAULT_SINK@ -5%")),
    Key("<XF86AudioRaiseVolume>", lazy.spawn("pactl set-sink-volume @DEFAULT_SINK@ +5%")),
    Key("<XF86AudioMute>", lazy.spawn("pactl set-sink-mute @DEFAULT_SINK@ toggle")),

    Key("M-r", lazy.spawn("rofi -show drun")),
    Key("M-s", lazy.spawn("alacritty -t 'ncspot' -e 'ncspot'")),
    Key("M-<Return>", lazy.spawn(terminal), desc="Launch terminal"),
    Key("M-S-<Return>", lazy.spawn(browser), desc="Open Firefox"),
    
    KeyChord([mod], "e", [
        Key("c", lazy.spawn("emacsclient -cs 'doom -e '(erc)'"), desc="Spawn erc with emacs client"),
        Key("e", lazy.spawn("emacsclient -cs 'doom' -a 'emacs'"), desc="Spawn emacs client"),
        Key("n", lazy.spawn("emacsclient -cs 'doom' -e '(elfeed)'"), desc="Spawn elfeed with emacs client"),
    ], mode="Emacs Apps"),

    KeyChord([mod, "shift"], "e", [
        Key("d", lazy.spawn("emacsclient -cs 'doom' -a 'emacs'"), desc="Spawn Doom Emacs client"),
        Key("j", lazy.spawn("emacsclient -cs 'jmacs' -a 'emacs --with-profile=jmacs'"), desc="Spawn Jmacs client"),
    ], mode="Emacs Profiles"),


        

    

    Key("C-<grave>", lazy.spawn("dunstctl close")),
]

#+end_src

** Group Bindings
This sets up the bindings for my groups - it works with KeyChords.
#+begin_src python
for group in groups:
    keys.extend([
      Key("M-{}".format(group.name), lazy.group[group.name].toscreen(), desc="Switch to group {}".format(group.name)),
      Key("M-S-{}".format(group.name), lazy.window.togroup(group.name), desc="Move focused window to group {}".format(group.name)) 
    ])

#+end_src

* Layouts
I have only a few layouts I’d like to use - a master/stack layout like in XMonad, and then a maximized layout. However, I also like to set up my floating layouts here.
** Theming
I like to have a consistant look for my layouts.
#+begin_src python
layout_theme = {
    "margin": 10,
    "border_focus": colors['purple'],
    "border_normal": colors['bg'],
    "border_width": 2
}
#+end_src

** My Main Layouts
#+begin_src python
layouts = [
    layout.MonadTall(**layout_theme),
    layout.Max(**layout_theme),
]
#+end_src

** Floating Layout
#+begin_src python

floating_layout = layout.Floating(float_rules=[
    # Run the utility of `xprop` to see the wm class and name of an X client.
    *layout.Floating.default_float_rules,
    Match(wm_class='confirmreset'),  # gitk
    Match(wm_class='makebranch'),  # gitk
    Match(wm_class='maketag'),  # gitk
    Match(wm_class='ssh-askpass'),  # ssh-askpass
    Match(title='branchdialog'),  # gitk
    Match(title='pinentry'),  # GPG key password entry
    Match(wm_class='pinentry-gtk-2'), 
], **layout_theme)
#+end_src

* Bars
** Theming
#+begin_src python
widget_defaults = dict(
    font=fonts['text'],
    fontsize=14,
    padding=3,
    background = colors['bg'],
    foreground = colors['fg'],
    theme_path = "/usr/share/icons/Paper/16x16/panel/"
)

extension_defaults = widget_defaults.copy()
#+end_src
*** Arrow Functions
#+begin_src python
def draw_arrow_right(bg,fg,font_size=33):
    "Creates a textbox widget with a right-pointing arrow."
    return widget.TextBox(text="",
                          padding=0,
                          fontsize=font_size,
                          background=bg,
                          foreground=fg)

def draw_arrow_left(bg,fg,font_size=33):
    "Creates a textbox widget with a right-pointing arrow."
    return widget.TextBox(text="",
                          padding=0,
                          fontsize=font_size,
                          background=bg,
                          foreground=fg)
#+end_src

** Main Bar
#+begin_src python
mainbar = bar.Bar([
    widget.Sep(linewidth=0,
               padding=6),
    widget.GroupBox(disable_drag=True,
                    block_highlight_text_color=colors['fg'],
                    active=colors['fg'],),
    draw_arrow_right(colors['blue'],
                     colors['bg']),
    widget.TextBox(text="",
                   font=fonts['material'],
                   fontsize = 12,
                   background=colors['blue']),
    widget.Clock(format="%H:%M - %a %d %b",
                 background=colors['blue']),

    draw_arrow_right(colors['purple'],
                     colors['blue']),
    widget.CurrentLayout(background=colors['purple']),
    draw_arrow_right(colors['bg'],
                     colors['purple']),
    #widget.Spacer(),
    widget.WindowName(),
    draw_arrow_left(colors['bg'],
                    colors['orange']),
    widget.WiFiIcon(background=colors['orange'],
                    active_colour = colors['fg'],
                    inactive_colour = colors['gray'],
                    padding=7,
                    foreground=colors['fg']),


    draw_arrow_left(colors['orange'],
                    colors['purple']),
    widget.TextBox(text="",
                   font = fonts['material'],
                   fontsize=16,
                   background=colors['purple']),

    widget.Bluetooth(hci="/dev_90_7A_58_A6_A0_0A",
                     background=colors['purple']),


    draw_arrow_left(colors['purple'],
                    colors['green']),


    widget.GenPollText(update_interval=None,
                       func=lambda: subprocess.check_output(os.path.expanduser("~/.dotfiles/.config/qtile/scripts/volicon.sh")).decode('utf-8'),
                       font=fonts['material'],
                       fontsize=16,
                       background=colors['green']),

    widget.GenPollText(update_interval=None,
                       func=lambda: subprocess.check_output(os.path.expanduser("~/.dotfiles/.config/qtile/scripts/printvol.sh")).decode('utf-8'),
                       background=colors['green']),

], 30)
#+end_src

* Screens
Screens are your monitors in qtile.
#+begin_src python
screens = [
    Screen(top = mainbar),
]
#+end_src


* Hooks
Hooks are scripts that can be automated in python - an example would be an init script for setting wallpapers, starting a compositor, etc.
** Autostart
This script calls some functions to automatically start.
#+begin_src python
@hook.subscribe.startup_once
def autostart():
    home = os.path.expanduser('~')
    subprocess.call([home + '/.config/qtile/scripts/autostart.sh'])
#+end_src

*** Bash Script
:PROPERTIES:
:header-args:sh: :tangle scripts/autostart.sh
:END:

#+begin_src sh :shebang "#!/usr/bin/env bash"
~/.dotfiles/.screenlayout/netbook-366-768.sh
xset b off
pulseaudio --start
picom -b 
feh --bg-center ~/Pictures/wallpapers/gruvbox/pacman.png
redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq -r '"\(.location.lat):\(.location.lng)"') &
emacs --daemon &
emacs --with-profile=jmacs --daemon &
#+end_src

** Volume
*** Percent
:PROPERTIES:
:header-args:sh: :tangle scripts/printvol.sh
:END:
#+begin_src sh :shebang "#!/usr/bin/env bash"
VOL=$(pacmd list-sinks|grep -A 15 '* index'| awk '/volume: front/{ print $5 }' | sed 's/[%|,]//g' | xargs)

MUTED=$(pacmd list-sinks|grep -A 15 '* index'|awk '/muted:/{ print $2 }')

if [[ $MUTED == "yes" ]] 
then
    printf "Muted"
else
    printf "%s%%" "$VOL"
fi
#+end_src
