variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  before_script:
    - apk add --update --no-cache git npm
  script:
    # - hugo --enableGitInfo -b "https://jhilker.gitlab.io"
    - npm ci --cache .npm --prefer-offline
    - hugo --minify
  except:
    - main

pages:
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  before_script:
    - apk add --update --no-cache git npm
  script:
    # - hugo --enableGitInfo -b "https://jhilker.gitlab.io"
    - npm ci --cache .npm --prefer-offline
    - hugo --minify
  artifacts:
    paths:
      - public
  only:
    - main
